### ISSUE TITLE
NameError: uninitialized constant Celluloid::Signals

### ISSUE THREAD

**Issue by fbjork** [chrisroberts/krakow#35]
when I try the following in `irb`:

``` ruby
p = Krakow::Producer.new(host: '127.0.0.1', port: '4150', topic: 'orders')
```

I get the following exception:

``` ruby
NameError: uninitialized constant Celluloid::Signals
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/krakow-0.4.2/lib/krakow/consumer.rb:36:in `<class:Consumer>'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/krakow-0.4.2/lib/krakow/consumer.rb:5:in `<module:Krakow>'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/krakow-0.4.2/lib/krakow/consumer.rb:3:in `<top (required)>'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/krakow-0.4.2/lib/krakow/connection.rb:66:in `<class:Connection>'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/krakow-0.4.2/lib/krakow/connection.rb:6:in `<module:Krakow>'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/krakow-0.4.2/lib/krakow/connection.rb:3:in `<top (required)>'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/krakow-0.4.2/lib/krakow/producer.rb:66:in `connect'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/krakow-0.4.2/lib/krakow/producer.rb:46:in `initialize'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/calls.rb:28:in `public_send'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/calls.rb:28:in `dispatch'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/call/sync.rb:16:in `dispatch'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/cell.rb:50:in `block in dispatch'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/cell.rb:76:in `block in task'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/actor.rb:363:in `block in task'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/task.rb:57:in `block in initialize'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/task/fibered.rb:14:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/call/sync.rb:45:in `value'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/proxy/sync.rb:40:in `method_missing'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid/proxy/cell.rb:20:in `_send_'
    from /Users/fredrik.bjork/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0.pre15/lib/celluloid.rb:198:in `new'
    from (irb):4
```

**Comment by mschneider82** [comment]
Hi, i got the same errors, try downgrading celluloid to 0.16.0, this will work fine.

**Comment by xoen** [comment]
We just stumbled on the same problem.
Krakow's dependencies should probably be version locked to be on the safe side: https://github.com/chrisroberts/krakow/blob/master/krakow.gemspec#L13

e.g. `s.add_runtime_dependency 'celluloid', '~> 0.16.0'`
